{% set name = "pystan" %}
{% set version = "2.16.0.0" %}
{% set sha256sum = "6061f6d327ff4b445eeee9a489d880f3d51782f638d70481d373b643568b2e92" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256sum }}
  #patches:
  #  - patches/0001-Disable-boost-quadmath.patch

build:
  number: 1
  skip: True  # [win and py27]
  features:
    - vc14  # [win and py35]
    - vc14  # [win and py36]
  detect_binary_files_with_prefix: False

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.7
    - cython >=0.22,!=0.25.1

  run:
    - python
    - numpy >=1.7
    - cython >=0.22,!=0.25.1
    - matplotlib

test:
  imports:
    - pystan

about:
  home: http://mc-stan.org/interfaces/pystan.html
  license: GPLv3
  license_file: LICENSE
  summary: Python interface to Stan, a package for Bayesian inference
  description: |
    PyStan provides a Python interface to Stan, a package for Bayesian
    inference using the No-U-Turn sampler, a variant of Hamiltonian Monte
    Carlo.
  doc_url: https://pystan.readthedocs.org/
  dev_url: https://github.com/stan-dev/pystan

extra:
  recipe-maintainers:
    - rmax
